<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\ShitpostBot.Application\ShitpostBot.Application.csproj" />
    <ProjectReference Include="..\ShitpostBot.Infrastructure\ShitpostBot.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="DSharpPlus" />
    <PackageReference Include="FastEndpoints" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\ShitpostBot.Application\1984.txt" Link="1984.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
