// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShitpostBot.Infrastructure;

#nullable disable

namespace ShitpostBot.Infrastructure.Migrations
{
    [DbContext(typeof(ShitpostBotDbContext))]
    partial class ShitpostBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShitpostBot.Domain.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ChatChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChatGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChatMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EvaluatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PostedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PosterId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("TrackedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostedOn");

                    b.HasIndex("PosterId");

                    b.ToTable("Post");

                    b.HasDiscriminator<int>("Type");
                });

            modelBuilder.Entity("ShitpostBot.Domain.ImagePost", b =>
                {
                    b.HasBaseType("ShitpostBot.Domain.Post");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("ShitpostBot.Domain.LinkPost", b =>
                {
                    b.HasBaseType("ShitpostBot.Domain.Post");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ShitpostBot.Domain.Post", b =>
                {
                    b.OwnsOne("ShitpostBot.Domain.PostStatistics", "Statistics", b1 =>
                        {
                            b1.Property<long>("PostId")
                                .HasColumnType("bigint");

                            b1.Property<bool>("Placeholder")
                                .HasColumnType("boolean");

                            b1.HasKey("PostId");

                            b1.ToTable("Post");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.OwnsOne("ShitpostBot.Domain.PostStatisticsMostSimilarTo", "MostSimilarTo", b2 =>
                                {
                                    b2.Property<long>("PostStatisticsPostId")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("SimilarToPostId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal>("Similarity")
                                        .HasColumnType("numeric(19,17)");

                                    b2.HasKey("PostStatisticsPostId");

                                    b2.ToTable("Post");

                                    b2.WithOwner()
                                        .HasForeignKey("PostStatisticsPostId");
                                });

                            b1.Navigation("MostSimilarTo");
                        });

                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
